services:
  mysql-db:
    ports:
      - "3307:3306"
    image: mysql:latest
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_PASSWORD=root
    volumes:
        - db_data:/var/lib/mysql
    networks:
      my-network:

  backend:
    ports:
      - "8080:8080"
    image: somesh11/springproject:02
    environment:
      - MYSQL_HOST=mysql-db
      - MYSQL_DATABASE=mydb
      - MYSQL_USER=root
      - MYSQL_PASSWORD=root
      - MYSQL_PORT=3307
    networks:
      my-network:
    depends_on:
      - mysql-db

  frontend:
    ports:
      - "3000:3000"
    image: somesh11/frontend:02
    depends_on:
      - mysql-db
      - backend
    networks:
      my-network:

volumes:
  db_data:
networks:
  my-network:
    driver: bridge